// Catalog data — real entries from the Е-Праздник spreadsheets.
// Each program has an accent color + an iconKey that maps to a placeholder
// "icon slot" in the UI. The client replaces these with final icons later.

const PROGRAMS = [
  {
    id: 'frozen',  iconKey: 'snowflake', monogram: 'ХС',
    title: 'Холодное Сердце',
    subtitle: 'Тайна кристаллов Эренделла',
    accent: '#3d6fa8', tint: '#eaf1fa',
    tags: [{ label: 'сюжетная', color: 'blue' }, { label: 'КРИО', color: 'purple' }, { label: 'премиум', color: 'pink' }],
    status: { label: 'готово к продаже', color: 'green', dot: '🟢' },
    audience: 'B2C', age: '5–12 лет', duration: '1,5 часа',
    actors: 'Эльза, Анна, Кристофф, Тумрана + Олаф',
    priceFrom: 182000,
  },
  {
    id: 'harry',   iconKey: 'bolt', monogram: 'ГП',
    title: 'Гарри Поттер',
    subtitle: 'Школа волшебства приглашает',
    accent: '#7a4a1f', tint: '#f4ecdf',
    tags: [{ label: 'сюжетная', color: 'brown' }, { label: 'квест', color: 'orange' }],
    status: { label: 'в работе', color: 'yellow', dot: '🟡' },
    audience: 'B2C', age: '7–14 лет', duration: '2 часа',
    actors: 'Гарри, Гермиона, Рон, Дамблдор, Северус + Хагрид',
    priceFrom: 215000,
  },
  {
    id: 'alice',   iconKey: 'card', monogram: 'АС',
    title: 'Алиса в Стране Чудес',
    subtitle: 'Чаепитие у Шляпника',
    accent: '#6a4d8c', tint: '#efeaf6',
    tags: [{ label: 'сюжетная', color: 'purple' }, { label: 'театр', color: 'pink' }],
    status: { label: 'в работе', color: 'yellow', dot: '🟡' },
    audience: 'B2C', age: '5–10 лет', duration: '1,5 часа',
    actors: 'Шляпник, Алиса, Красная и Белая Королевы + Заяц',
    priceFrom: 168000,
  },
  {
    id: 'paw',     iconKey: 'paw', monogram: 'ЩП',
    title: 'Щенячий Патруль',
    subtitle: 'Спасательная миссия',
    accent: '#c47a14', tint: '#fbefd5',
    tags: [{ label: 'сюжетная', color: 'yellow' }, { label: 'малыши', color: 'orange' }],
    status: { label: 'в работе', color: 'yellow', dot: '🟡' },
    audience: 'B2C', age: '3–6 лет', duration: '1 час',
    actors: 'Маршал, Гонщик, Скай + ростовые Маршал и Гонщик',
    priceFrom: 124000,
  },
  {
    id: 'heroes',  iconKey: 'shield', monogram: 'СГ',
    title: 'Супергерои',
    subtitle: 'Тренировка молодого героя',
    accent: '#b13a3a', tint: '#f9e8e8',
    tags: [{ label: 'квест', color: 'red' }, { label: 'актив', color: 'orange' }],
    status: { label: 'не хватает материалов', color: 'red', dot: '🔴' },
    audience: 'B2C', age: '6–11 лет', duration: '1,5 часа',
    actors: 'Команда супергероев + Зелёный Гоблин',
    priceFrom: 156000,
  },
  {
    id: 'princess',iconKey: 'crown', monogram: 'ПР',
    title: 'Принцессы',
    subtitle: 'Бал в королевском дворце',
    accent: '#a85978', tint: '#f6e7ee',
    tags: [{ label: 'сюжетная', color: 'pink' }, { label: 'премиум', color: 'purple' }],
    status: { label: 'в работе', color: 'yellow', dot: '🟡' },
    audience: 'B2C', age: '5–9 лет', duration: '1,5 часа',
    actors: 'Ариэль, Золушка, Белоснежка + Чудовище',
    priceFrom: 174000,
  },
  {
    id: 'ladybug', iconKey: 'ladybug', monogram: 'ЛБ',
    title: 'Леди Баг',
    subtitle: 'Спаси Париж от Бражника',
    accent: '#c43a3a', tint: '#faeaea',
    tags: [{ label: 'сюжетная', color: 'red' }, { label: 'актив', color: 'gray' }],
    status: { label: 'в работе', color: 'yellow', dot: '🟡' },
    audience: 'B2C', age: '7–12 лет', duration: '1,5 часа',
    actors: 'Леди Баг, Супер Кот, Бражник',
    priceFrom: 152000,
  },
  {
    id: 'robots',  iconKey: 'robot', monogram: 'РБ',
    title: 'Роботы',
    subtitle: 'Лаборатория искусственного интеллекта',
    accent: '#4a5360', tint: '#ebedf0',
    tags: [{ label: 'STEM', color: 'gray' }, { label: 'актив', color: 'blue' }],
    status: { label: 'не хватает материалов', color: 'red', dot: '🔴' },
    audience: 'B2C', age: '8–14 лет', duration: '2 часа',
    actors: 'Инженеры, Робот-наставник',
    priceFrom: 198000,
  },
  {
    id: 'turtles', iconKey: 'shell', monogram: 'ЧН',
    title: 'Черепашки Ниндзя',
    subtitle: 'Тренировка в подземном додзё',
    accent: '#3a7a4d', tint: '#e7f1ea',
    tags: [{ label: 'квест', color: 'green' }, { label: 'актив', color: 'orange' }],
    status: { label: 'не хватает материалов', color: 'red', dot: '🔴' },
    audience: 'B2C', age: '7–12 лет', duration: '1,5 часа',
    actors: 'Леонардо, Микеланджело + ниндзя',
    priceFrom: 162000,
  },
  {
    id: 'pirates', iconKey: 'anchor', monogram: 'ПИ',
    title: 'Пираты',
    subtitle: 'Карта сокровищ Карибского моря',
    accent: '#2e4a66', tint: '#e7ecf3',
    tags: [{ label: 'квест', color: 'blue' }, { label: 'актив', color: 'brown' }],
    status: { label: 'в работе', color: 'yellow', dot: '🟡' },
    audience: 'B2C', age: '6–12 лет', duration: '1,5 часа',
    actors: 'Капитан Джек, пираты Ж1/Ж2 + М',
    priceFrom: 148000,
  },
  {
    id: 'unicorn', iconKey: 'horn', monogram: 'ЕД',
    title: 'Единорожки',
    subtitle: 'Радужная поляна желаний',
    accent: '#a050a8', tint: '#f3e7f4',
    tags: [{ label: 'сюжетная', color: 'pink' }, { label: 'малыши', color: 'purple' }],
    status: { label: 'в работе', color: 'yellow', dot: '🟡' },
    audience: 'B2C', age: '3–7 лет', duration: '1 час',
    actors: 'Единорожки 2, ростовые + световой полуконь',
    priceFrom: 134000,
  },
  {
    id: 'pajama',  iconKey: 'moon', monogram: 'ПВ',
    title: 'Пижамная вечеринка',
    subtitle: 'Подростковый сценарий',
    accent: '#4a3a8a', tint: '#ebebf5',
    tags: [{ label: 'формат', color: 'purple' }, { label: 'подростки', color: 'gray' }],
    status: { label: 'не хватает материалов', color: 'red', dot: '🔴' },
    audience: 'B2C', age: '9–14 лет', duration: '3 часа',
    actors: 'Ведущие на выбор + танцевальные челленджи',
    priceFrom: 142000,
  },
];

// "Холодное Сердце" — full detail content lifted from the xlsx
const FROZEN = {
  legend:
    'Волшебная сюжетная программа, в которой дети вместе с Эльзой отправляются по следам магии Эренделла, чтобы пробудить древние кристаллы, спасти коронацию и вернуть силу Сердцу Ледяного Королевства.',
  characters: [
    { name: 'Эльза', role: 'королева Эренделла' },
    { name: 'Анна', role: 'её сестра' },
    { name: 'Кристофф', role: 'добытчик льда' },
    { name: 'Принц Ханс', role: 'антагонист' },
    { name: 'Тумрана', role: 'хранительница магии' },
    { name: 'Олаф', role: 'ростовая кукла' },
  ],
  activities: [
    { name: 'Оленья тропа',           note: 'разогрев и знакомство с Кристоффом' },
    { name: 'Ледяной страж',          note: 'квест-командное испытание' },
    { name: 'Зов кристалла',          note: 'музыкально-двигательный номер' },
    { name: 'Пробуждение кристалла',  note: 'спецэффект — крио + свет' },
    { name: 'Зонтики Олафа',          note: 'игра-разрядка' },
    { name: 'Любимое лакомство Олафа',note: 'мини-МК со сладкой ватой' },
    { name: 'Тёплые шарфы Кристоффа', note: 'тактильный мастер-класс' },
  ],
  finale:
    'Кристаллы полностью пробуждаются, загорается Сердце Ледяного Королевства, магия возвращается в Эренделл, и праздник завершается торжественной коронацией именинницы и настоящим ледяным чудом.',
  // Matrix columns from the MEDIA HUB sheet
  readiness: [
    { state: 'done',    label: 'Продающее описание',     col: 'G' },
    { state: 'done',    label: 'Короткое описание',      col: 'H' },
    { state: 'done',    label: 'Техническое описание',   col: 'F' },
    { state: 'done',    label: 'Фотосессия',             col: 'I' },
    { state: 'done',    label: 'Фото с праздников',      col: 'J' },
    { state: 'done',    label: 'Афиша',                  col: 'K' },
    { state: 'done',    label: 'FULL Тизер',             col: 'L' },
    { state: 'done',    label: 'Reels-тизер',            col: 'M' },
    { state: 'wip',     label: 'Live с праздника',       col: 'N' },
    { state: 'missing', label: 'Лендинг / презентация',  col: 'O' },
    { state: 'done',    label: 'Актуальные цены',        col: 'P' },
    { state: 'wip',     label: 'КП-шаблон',              col: '—' },
    { state: 'missing', label: 'SMM-пост',               col: '—' },
  ],
};

// Spreadsheet rows for the "конструктор" screen — real data from sheet "ХОЛОДНОЕ СЕРДЦЕ"
const SHEET_ROWS = [
  { kind: 'section', label: 'ВЕЛКОМ-ЗОНА' },
  { n: '1', name: 'Артист (говорящий актёр)', desc: 'Морозный помощник м. / Морозный помощник ж.', dur: '30 мин', price: 3500, qty: 6, actors: 1, total: 21000, margin: 0.66 },
  { n: '2', name: 'МК «Волшебные снежные шары»', desc: 'Дети создают шар с фигуркой и кружащимся снегом', dur: '30 мин', price: 900, qty: 10, actors: 1, total: 13000, margin: 0.76 },
  { n: '3', name: 'Магическое создание снега (фокус)', desc: 'Эффектный номер открытия', dur: '5 мин', price: 5000, qty: 1, actors: 1, total: 5000, margin: 0.94 },
  { n: '4', name: 'Голубая сладкая вата', desc: 'Гастрозона «Сладкое облако»', dur: '30 мин', price: 9500, qty: 1, actors: 1, total: 9500, margin: 0.77 },
  { n: '5', name: 'Синий поп-корн — повар', desc: 'Гастрозона «Морозный хруст»', dur: '30 мин', price: 10500, qty: 1, actors: 1, total: 10500, margin: 0.80 },
  { kind: 'total', label: 'ИТОГО ВЕЛКОМ', total: 59000, margin: 0.75 },
  { kind: 'section', label: 'ИГРОВАЯ ПРОГРАММА' },
  { n: '1', name: 'Актёры', desc: 'Анна, Эльза, Кристофф, Принц Ханс, Тумрана', dur: '1,5 ч', price: 5500, qty: 1, actors: 2, total: 11000, margin: 0.69 },
  { n: '2', name: 'Ростовой Олаф', desc: 'Снеговик встречает гостей и участвует в номерах', dur: '1 ч', price: 6500, qty: 1, actors: 1, total: 6500, margin: 0.82 },
  { n: '3', name: 'Снегогенератор', desc: 'Спецэффект «Дыхание Северного Ветра»', dur: 'весь праздник', price: 5500, qty: 1, actors: 0, total: 5500, margin: 0.95 },
];

window.PROGRAMS = PROGRAMS;
window.FROZEN = FROZEN;
window.SHEET_ROWS = SHEET_ROWS;
